# wrangler.toml

# 建议使用您在 Cloudflare Pages 上的项目名
name = "my-nextjs-blog-8v0" 

# 使用一个近期的日期，这会启用最新的功能和修复
compatibility_date = "2024-07-05"

# 这是解决问题的关键所在
# 启用 Node.js 兼容性标志，让 Cloudflare Pages 提供 fs, path 等 Node.js API
compatibility_flags = [ "nodejs_compat" ]
